### ISSUE TITLE
Wrong type argument: sequencep, :input-buffer

### ISSUE THREAD

**Issue by manuel-uberti** [tomalexander/orgmode-mediawiki#13]
Hi,

I've just installed this package from MELPA. I am trying to export a simple Org file. This is its content:
```
#+STARTUP: showall
#+TITLE: prova media wiki

* prova
** ciao
```
Whether I pick "To temporary buffer" (```M```) or "To file" (```m```), I always get this error: http://pastebin.com/kTbkUpd8

**Comment by braegel** [comment]
I'm getting the same error. Manual install.
* This is GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)
 of 2014-03-07 on lamiak, modified by Debian
* Org-mode version 8.3.1 /usr/share/emacs/42.3/lisp/org

**Comment by deepestthought42** [comment]
After being annoyed by the same error, I looked into this a bit. Version 8.3 of org-mode has seen a signature change in ```org-export-collect-footnote-definitions``` (http://orgmode.org/Changes.html), so ```org-mw-footnote-section``` needs to be updated to reflect this change. For me, changing ```org-mw-footnote-section``` to: 
```
(org-export-collect-footnote-definitions
                    info (plist-get info :parse-tree))
```

worked, but I don't know what other problems this might cause ...

Cheers!
