### ISSUE TITLE
org code/verbatim markup causes error

### ISSUE THREAD

**Issue by JosefAssad** [tomalexander/orgmode-mediawiki#15]
An org file containing the following:

`=test=`

or

`~test~`

Causes `org-mw-export-to-mediawiki` and `org-mw-export-as-mediawiki` to fail with the message `org-mw-verbatim: Wrong type argument: stringp, nil`.

**Comment by BrendanLeber** [comment]
I'm also seeing this error with org-mode v8.2.10 and ox-mediawiki version 20150923.902.

**Comment by flowsta** [comment]
Hi

is this error still open? I am suffering the same error messages with Org mode version 9.0 (9.0-elpa @ org-20161102/ and ox-mediawiki  20161115.541.

**Comment by hexmode** [comment]
does the above  patch fix it for you?

**Comment by dov** [comment]
I had the same problem, and indeed pavanky's patch solved it! 👍
