### ISSUE TITLE
Subtree export

### ISSUE THREAD

**Issue by phaebz** [tomalexander/orgmode-mediawiki#3]
Is subtree export supposed to work? I get the following error on a very simple subtree:

```
Initializing asynchronous export process
save-current-buffer: Wrong type argument: stringp, (lambda (p status) (let ((proc-buffer (process-buffer p))) (when (eq (process-status p) (quote exit)) (unwind-protect (if (zerop (process-exit-status p)) (unwind-protect (let ((results (with-current-buffer proc-buffer ... ... ...))) (funcall (lambda (output) (with-current-buffer ... ... ... ... ... ... ...)) results)) (unless org-export-async-debug (and (get-buffer proc-buffer) (kill-buffer proc-buffer)))) (org-export-add-to-stack proc-buffer nil p) (ding) (message "Process '%s' exited abnormally" p)) (unless org-export-async-debug (delete-file "/var/folders/03/g441ctw52xjgcv3mhhw3053h0000gn/T/org-export-process2711hlu"))))))
Process 'org-export-process' exited abnormally
```

if subtree export is supposed to work, please give me a hint on where to look next.

**Comment by SebastianRiedel** [comment]
Getting the same error when trying to export a subtree:

    Initializing asynchronous export process
    save-current-buffer: Wrong type argument: stringp, (lambda (p status) (let ((proc-buffer (process-buffer p))) (when (eq (process-status p) (quote exit)) (unwind-protect (if (zerop (process-exit-status p)) (unwind-protect (let ((results (with-current-buffer proc-buffer ... ... ...))) (funcall (lambda (output) (with-current-buffer ... ... ... ... ... ... ...)) results)) (unless org-export-async-debug (and (get-buffer proc-buffer) (kill-buffer proc-buffer)))) (org-export-add-to-stack proc-buffer nil p) (ding) (message "Process '%s' exited abnormally" p)) (unless org-export-async-debug (delete-file "/tmp/org-export-process14099ije"))))))
    Process 'org-export-process' exited abnormally

Does anyone see where the problem is?
